all:
	g++ -Wall -Wno-parentheses -O2 -o bzcat bzcat.cpp
	g++ -Wall -Wno-parentheses -O2 -o bzcat2 bzcat2.cpp
	gcc -Wall -Wno-parentheses -O2 -o bzcatc bzcat.c
	javac Bzcat.java

clean:
	rm -v *.class bzcat

