all:
	g++ -Wall -Wno-parentheses -O2 -o bzcat bzcat.cpp
	g++ -Wall -Wno-parentheses -O2 -o bzcat2 bzcat2.cpp
	g++ -Wall -Wno-parentheses -O2 -o bzcat3 bzcat3.cpp
	javac Bzcat.java

clean:
	rm -v *.class bzcat

