#include "globals.h"

BookEntry *Book;
DWORD hashkey, hashbd;
HashVal *hashcode;
hashentry *ttable;
FILE *hashfile;
Leaf *Tree;
short TrPnt[MAXDEPTH], PieceList[2][16], PawnCnt[2][8];
short castld[2], Mvboard[64], svalue[64];
Flags flag;
short opponent, computer, Awindow, Bwindow, dither, INCscore;
long ResponseTime, ExtraTime, Level, et, et0, time0, ft;
long NodeCnt, ETnodes, EvalNodes;
short player, xwndw, rehash;
GameRec *GameList;
short Sdepth, GameCnt, Game50, MaxSearchDepth, epsquare, contempt;
TimeControlRec TimeControl;
short TCflag, TCmoves, TCminutes, OperatorTime;
WORD hint, PrVar[MAXDEPTH];
short Pindex[64], PieceCnt[2], c1, c2;
short mtl[2], pmtl[2], emtl[2], hung[2];
short HasKnight[2], HasBishop[2], HasRook[2], HasQueen[2];
short ChkFlag[MAXDEPTH], CptrFlag[MAXDEPTH], PawnThreat[MAXDEPTH];
short Pscore[MAXDEPTH], Tscore[MAXDEPTH];
short stage, stage2, Developed[2], *distdata, *taxidata, board[64], color[64];
BYTE *history, *nextpos, *nextdir;
const short otherside[3] = {1, 0, 2};
HWND hComputerColor, hComputerMove, hWhosTurn;
HWND hClockComputer, hClockHuman;
HWND hMsgComputer, hMsgHuman, hStats;
GLOBALHANDLE hBook = 0;
COLORREF clrBackGround, clrBlackSquare, clrWhiteSquare;
COLORREF clrBlackPiece, clrWhitePiece, clrText;
HINSTANCE hInst;
HACCEL hAccel;
TCHAR mvstr[4][6];
long evrate;
PIECEBITMAP pieces[7];
short boarddraw[64], colordraw[64];

